name: Run build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          path: dist
